#!/bin/bash

VERSION=$(cat ./VERSION)
PKGVERSION="$VERSION"
GITCOMMIT=$(git rev-parse --short HEAD)

if test -n "$(git status --porcelain)"
then
	GITCOMMIT="$GITCOMMIT-dirty"
	PKGVERSION="$PKGVERSION-$(date +%Y%m%d%H%M%S)-$GITCOMMIT"
fi

DOCKER_PACKAGE=github.com/dotcloud/docker
export GOPATH="${PWD}"
SRC_DIR="$GOPATH/src"
DOCKER_DIR="$SRC_DIR/$DOCKER_PACKAGE"

DOCKER_BASE=$(dirname "${DOCKER_DIR}")
if [ ! -d "${DOCKER_BASE}" ]; then
	mkdir -p "${DOCKER_BASE}"
fi

if [ ! -h "${DOCKER_DIR}" ]; then
	ln -s ../../../ "${DOCKER_DIR}"
fi

for i in third_party/*; do
	if [ "$i" = "third_party/src" ]; then
		continue
	fi
	cp -R "$i" src/
done

cd $DOCKER_DIR
CGO_ENABLED=0 go build -a -o bin/docker -ldflags "-X main.GITCOMMIT $GITCOMMIT  -X main.VERSION $PKGVERSION -d -w" ./docker
